---
- name: Installs a package and prints the result
  hosts: all
  tasks:
    - name: Install the package
      yum:
        name: mc
        state: installed
      register: install_result

    - debug: var=install_result
