---
- name: Install and configure web service
  hosts:
    - server*.lab.example.com
  tasks:
    - name: Import the web_tasks.yml task file
      import_tasks: tasks/web_tasks.yml

    - name: Install firewalld
      yum:
        name: firewalld
        state: latest

    - name: Enable and start the firewall
      service:
        name: firewalld
        enabled: true
        state: started
    
    - name: Open the port for http
      firewalld:
        service: http
        immediate: true
        permanent: true
        state: enabled

handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted
