---
- name: Configure WebServerS
  hosts: webservers
  become: true
  vars:
          installation_packages:
                  - https
                  - mariadb-server

  tasks:
          - name: Package Installed
            yum:
                    name: "{{ item }}"
                    state: latest

          - name: Service Running
            service:
                    name: "{{ item }}"
                    state: started
                    enabled: true
            loop: "{{ installation_package }}"

          - name: HTTP Allowed Through Firewall
            firewalld:
                    service: http
                    state: enabled
                    immediate: true
                    permanent: true
          - name: Deploy Web Page
            template:
                    src: index.html.j2
                    dest: /var/www/html/index.html
                    owner: root
                    group: root
                    mode: 0644
